<?php
include 'db.php';

// This ensures the hash is generated by YOUR server
$password = '123456';
$hashed = password_hash($password, PASSWORD_DEFAULT);
$email = 'jhsowrov079@gmail.com';

$sql = "UPDATE users SET password = ?, role = 'admin' WHERE email = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $hashed, $email);

if ($stmt->execute()) {
    echo "<h2>Success!</h2>";
    echo "The database has been updated with a fresh hash.<br>";
    echo "Email: <b>$email</b><br>";
    echo "Password: <b>123456</b><br><br>";
    echo "<a href='universal-login.php'>Go to Login Page</a>";
} else {
    echo "Error: " . $conn->error;
}
?>